services:
  backend:
    container_name: 'backend'
    build: /backend
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
      - /backend/node_modules/
    environment:
      - MQTT_HOST=emqx
      - MQTT_PORT='1883'

  frontend:
    container_name: 'frontend'
    build: /frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
      # change this to your local ip
      - BACKEND_URL=10.0.0.12
      - BACKEND_INTERNAL_URL=backend
      - BACKEND_PORT=5000
    
  emqx:
    image: emqx:5.3.1
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]"
    # volumes:
    #   - $PWD/emqx1_data:/opt/emqx/data
